import _NovelSite from './site';
import { EnumNovelSiteList, INovelSiteList } from './all/const';
export { EnumNovelSiteList, INovelSiteList };
export declare function requireNovelSiteClass(siteID: EnumNovelSiteList.NovelSiteAlphapolis | 'alphapolis'): INovelSiteList["NovelSiteAlphapolis"];
export declare function requireNovelSiteClass(siteID: EnumNovelSiteList.NovelSiteDemoBase | 'demo/base'): INovelSiteList["NovelSiteDemoBase"];
export declare function requireNovelSiteClass(siteID: EnumNovelSiteList.NovelSiteDemoDemo | 'demo/demo'): INovelSiteList["NovelSiteDemoDemo"];
export declare function requireNovelSiteClass(siteID: EnumNovelSiteList.NovelSiteDemoTree | 'demo/tree'): INovelSiteList["NovelSiteDemoTree"];
export declare function requireNovelSiteClass(siteID: EnumNovelSiteList.NovelSiteDmzjApi | 'dmzj/api'): INovelSiteList["NovelSiteDmzjApi"];
export declare function requireNovelSiteClass(siteID: EnumNovelSiteList.NovelSiteDmzj | 'dmzj'): INovelSiteList["NovelSiteDmzj"];
export declare function requireNovelSiteClass(siteID: EnumNovelSiteList.NovelSiteEsjzone | 'esjzone'): INovelSiteList["NovelSiteEsjzone"];
export declare function requireNovelSiteClass(siteID: EnumNovelSiteList.NovelSiteHetubook | 'hetubook'): INovelSiteList["NovelSiteHetubook"];
export declare function requireNovelSiteClass(siteID: EnumNovelSiteList.NovelSiteIqing | 'iqing'): INovelSiteList["NovelSiteIqing"];
export declare function requireNovelSiteClass(siteID: EnumNovelSiteList.NovelSiteKakuyomu | 'kakuyomu'): INovelSiteList["NovelSiteKakuyomu"];
export declare function requireNovelSiteClass(siteID: EnumNovelSiteList.NovelSiteMillionbook | 'millionbook'): INovelSiteList["NovelSiteMillionbook"];
export declare function requireNovelSiteClass(siteID: EnumNovelSiteList.NovelSiteNovelba | 'novelba'): INovelSiteList["NovelSiteNovelba"];
export declare function requireNovelSiteClass(siteID: EnumNovelSiteList.NovelSiteNovelup | 'novelup'): INovelSiteList["NovelSiteNovelup"];
export declare function requireNovelSiteClass(siteID: EnumNovelSiteList.NovelSiteSfacg | 'sfacg'): INovelSiteList["NovelSiteSfacg"];
export declare function requireNovelSiteClass(siteID: EnumNovelSiteList.NovelSiteSyosetu | 'syosetu'): INovelSiteList["NovelSiteSyosetu"];
export declare function requireNovelSiteClass(siteID: EnumNovelSiteList.NovelSiteUukanshu | 'uukanshu'): INovelSiteList["NovelSiteUukanshu"];
export declare function requireNovelSiteClass(siteID: EnumNovelSiteList.NovelSiteWebqxs | 'webqxs'): INovelSiteList["NovelSiteWebqxs"];
export declare function requireNovelSiteClass(siteID: EnumNovelSiteList.NovelSiteWenku8 | 'wenku8'): INovelSiteList["NovelSiteWenku8"];
export declare function requireNovelSiteClass(siteID: EnumNovelSiteList.NovelSiteX23qb | 'x23qb'): INovelSiteList["NovelSiteX23qb"];
export declare function requireNovelSiteClass<T extends typeof _NovelSite>(siteID: EnumNovelSiteList | string): T;
export default requireNovelSiteClass;
